# Generated by Django 5.2.8 on 2025-12-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='note_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
