# Generated by Django 5.2.8 on 2025-12-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_rename_note_date_expense_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
