# Generated by Django 5.2.8 on 2025-12-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_expense_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user_id',
            new_name='user',
        ),
    ]
